plugins:
  discourse_topic_management_enabled:
    default: false
  discourse_topic_management_hidden_category_id:
    type: category
    client: true
    default: ""
  discourse_topic_management_categories_remove_button_visible:
    type: category_list
    client: true
    default: ""
  discourse_topic_management_category_limits:
    type: list
    client: false
    default: ""
  discourse_topic_management_tag_limits:
    type: list
    client: false
    default: ""
  discourse_topic_notification_color:
    type: enum
    client: true
    default: "--secondary"
    choices:
      - "--primary"
      - "--secondary"
      - "--tertiary"
      - "--quaternary"
      - "--header_background"
      - "--header_primary"
      - "--highlight"
      - "--danger"
      - "--success"
      - "--love"
  discourse_topic_notification_background_color:
    type: enum
    client: true
    default: "--tertiary"
    choices:
      - "--primary"
      - "--secondary"
      - "--tertiary"
      - "--quaternary"
      - "--header_background"
      - "--header_primary"
      - "--highlight"
      - "--danger"
      - "--success"
      - "--love"
