plugins:
  discourse_topic_management_enabled:
    default: false
  discourse_topic_management_hidden_category_id:
    type: category
    client: true
    default: ""
  discourse_topic_management_categories_remove_button_visible:
    type: category_list
    client: true
    default: ""
  discourse_topic_management_reply_limit:
    default: 5
  discourse_topic_management_limited_categories:
    type: category_list
    client: true
    default: ""
  discourse_topic_management_limited_tags:
    type: list
    client: true
    default: ""
